#!/bin/sh

if [[ $USER != "root" ]]; then
    echo "this script is required to be run as root"
    exit 0
fi

echo -n "install user:"
read INSTALL_USER

export INSTALL_USER=$INSTALL_USER

# repos
echo -e "\n## Repos ##"

for file in repos/*; do
    if [[ $file == *.repo ]]; then
	echo -e "\ncopying $file to /etc/yum.repos.d/"
	cp repos/* /etc/yum.repos.d/
    fi

    if [[ $file == *.install ]]; then
	while read line; do
	    if [[ $line != "" ]] && [[ $line != "#"* ]]; then
		packages=$packages" $line"
	    fi
	done < $file

	echo -e "\ninstalling repo $file:"
	dnf install $packages

	packages=""
    fi
done

# packages
echo -e "\n## Packages ##"

for file in packages/*; do
    if [[ $file == *.pkglst ]]; then
	while read line; do
	    if [[ $line != "" ]] && [[ $line != "#"* ]]; then
		packages=$packages" $line"
	    fi
	done < $file

	echo -e "\ninstalling $file:"
	dnf install $packages
	
	packages=""
    fi
done

# other
echo -e "\n## Other ##"

for file in other/*; do
    if [[ $file == *.sh ]]; then
	echo -e "\nexecuting $file:"
	sh $file
    fi
done

echo -e "\nall done you should be good to go"
